// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int under = 0, over = 0;
		for (int i = 0; i < n; i++) {
			if (Math.random() > 0.5) {
				over ++;
			}
			else{
				under++;
			}
		}
		System.out.println("> 0.5: "+ over +" times");
		System.out.println("<= 0.5 :"+ under +" times");
		if (under != 0)
			System.out.println("Ratio: "+ (double) over / under );

	}
}
